### ISSUE TITLE
Ocean REST API - List Price Feed - Entries before 2021-08-11

### ISSUE THREAD

**Issue by cakebake** [JellyfishSDK/jellyfish#1456]
I'm currently fetching price data from the [endpoint `/prices/DFI-USD/feed` ](https://jellyfishsdk.com/ocean/prices/#list-price-feed)and I'm wondering that the oldest date is `2021-08-11 07:09:07+00:00` (block.medianTime), because the [DEX starts at November 2020](https://blog.defichain.com/defichain-dex-liquidity-mining-launching-monday-november-30th/). 
I got `48585` entries, `2021-08-11 07:09:07+00:00` to `2022-05-20 09:11:47+00:00` with `972` calls with `50` items per call.

Is there a way to get older prices? Thanks in advance - I hope I am in the right repo.

![newplot](https://user-images.githubusercontent.com/7462226/169510466-baee32f5-03b3-4699-9626-535b250ac29c.png)

**Comment by fuxingloh** [comment]
/area apps

Hey, you're querying the Aggregated Oracle Price Feed for Loan operations which is part of the [defiscan.live/oracles/DFI-USD](https://defiscan.live/oracles/DFI-USD) collection. The oracle was released some time around 2021 August with this txid: [a4492224b78b065d3c044e65e4968e9b326f1b19b615b50f79d3ab58df10f2c5](https://defiscan.live/transactions/a4492224b78b065d3c044e65e4968e9b326f1b19b615b50f79d3ab58df10f2c5)

If you're looking for DEX PoolPair history, you can check out this https://jellyfishsdk.com/ocean/poolpairs#list-pool-swaps-verbose, to only get "DFI-USD" prices you can query the USDC, USDT or DUSD pairs. The history takes into account composite swaps that are routed through the pairs, you need to filter out those if you're not interested in composite swap history. Since USDC and DUSD were introduced fairly late, your best bet would be to query USDT-DFI history.
