### ISSUE TITLE
reindex required after dexstats node reindex?

### ISSUE THREAD

**Issue by sancag** [JellyfishSDK/jellyfish#1598]
I am currently running a reindex of the new 2.9.0 node with ```-dexstats``` enabled. Will that require a reindex of leveldb?

**Comment by fuxingloh** [comment]
You should direct that question to DeFiCh/ain, since it's not within the scope of jellyfish.

However based on my understanding of the releases notes, `-dexstats` uses "live economy" implementation. That feature uses a rolling aggregator and will require reindexing from block=0 to get the accurate economy.

**Comment by sancag** [comment]
Thanks, the node needs indexing. Question is if whale needs it too

**Comment by fuxingloh** [comment]
Nope it won't require one

**Comment by sancag** [comment]
Perfect thanks
