### ISSUE TITLE
`/apps/whale-api` - Consolidation & Migration 

### ISSUE THREAD

**Issue by fuxingloh** [JellyfishSDK/jellyfish#977]
> As part of #580 consolidation efforts. 
> https://github.com/DeFiCh/whale

#### What would you like to be added:

Migration of the entire `DeFiCh/whale` project into `DeFiCh/jellyfish/apps/whale-api`.

/sig ecosystem
/area apps
/triage accepted

**Comment by kodemon** [comment]
@fuxingloh just a quick question here, this seems like an interesting undertaking but I am seeing 20+ open PRs in whale, would these need to go in before we can migrate over?

To me this looks like we need to copy the current state of the project then tailor it to jellyfish similar to ocean. So the whale packages goes into `jellyfish/packages` and the api portion goes into `apps/whale-api`.

Is there a good strategy/direction to do this cleanly, or is that something we need to figure out as part of this ticket? 😅

**Comment by fuxingloh** [comment]
> @fuxingloh just a quick question here, this seems like an interesting undertaking but I am seeing 20+ open PRs in whale, would these need to go in before we can migrate over?

Nope, we can move the issues over after we migrate in here.

> To me this looks like we need to copy the current state of the project then tailor it to jellyfish similar to ocean. So the whale packages goes into `jellyfish/packages` and the api portion goes into `apps/whale-api`.

Yup, you are right.

> Is there a good strategy/direction to do this cleanly, or is that something we need to figure out as part of this ticket? 😅

Need to figure this out along the way, but the implementation should follow suitable similar patterns on `/apps` and `/packages`. Perhaps also iterating the migration in instead of doing one large PR?

/assign @kodemon since you are interested? 🤓

**Comment by kodemon** [comment]
@fuxingloh Wanted to give you a quick update on this ticket as I have some things needing your input before I submit to a course of action.

I was working on this ticket throughout yesterday trying to set up a pathway that causes as little friction as possible. Mainly the idea is to attempt to port whale into jellyfish in a way that allows us to keep up with any updates to the current whale repo as we are still actively working on it. Unfortunately I am meeting some resistance, so want to outline my current thoughts and the challenges I am currently facing.

### Preferred Solution

My first thought is to start with only porting each whale package individually, and do so with minimal changes to the internals avoiding refactoring code. This way we can potentially simply just copy over files in whale as they get updated with minimal conflicts.

### Problems Encountered

Unfortunately after tinkering yesterday I have not found a graceful way to accomplish this. And the reason for this is the hard coupled dependencies between the `src` and `packages` in whale. Essentially you have the equivalent of a circular dependency structure which makes it difficult to do partial migration without changing code.

If we start by looking at `whale-api-client`, which from a implementation perspective is completely decoupled from `whale/src` but the problem lies with the unit tests. The unit tests are using `whale/src` to stub the service for testing. This is essentially `jellyfish/packages/whale-api-client` importing `apps/whale` to perform its unit tests, which I think is sort of an anti pattern here. I would like to see any `packages` being tested in isolation or only with dependencies on other `packages` not our `apps`.

Now if we did decide that this dependency coupling is fine, the secondary issue the way you need to modify the jellyfish setup to make this work _(which I have yet to achieve)_ since you have to start re-thinking how things are set up with `paths` for package resolution. I did several attempts to wire the pathing up in a way that allowed for no change to the code to simplify the porting of continual updates to `whale`. Unfortunately I'm encountering some issues with jest not reliably being able to resolve this structure. 

## Resolutions

This is where my blocker is currently, from what I am seeing there is no way to get this perfectly set up. One way we could potentially solve the coupling is to rewrite the tests in the packages to not depend on the apps. But that does require a significant effort of writing up a test base that isn't dependent on this setup. And I am not even sure if removing this dependency is the right way to test things. Eg. perhaps we need to test this package from the perspective of apps service being available.

The second thought I had was that we may want to move application specific testing into the apps. So perhaps we can move all the tests in `whale-api-client` into `apps/whale` and inadvertently test `whale-api-client` through `apps/whale`.

I think perhaps if we can take some temporary measures to avoid changing the code of our files we will have an easier time just copying the actual code from `whale` to `jellyfish` as it gets updated. And once we kill off `whale` we can refactor some of these internals once we are fully migrated?

----

Please grab me when you have some time to discuss so we can come to preferred set of actions to achieve this migration.

**Comment by kodemon** [comment]
Had a quick meet with the team to discuss an approach which made complete sense.

Just to follow up, I will focus on package migration first, then create new packages from any app side dependencies to resolve unit test dependency issues.

**Comment by fuxingloh** [comment]
As part of the #580 `ocean-api` transition, additional literature regarding the same problems and also resolution was carried out.

- https://github.com/DeFiCh/jellyfish/pull/909
- https://github.com/DeFiCh/jellyfish/pull/926
- https://github.com/DeFiCh/jellyfish/pull/929

> In #929 - Different from the whale development testing style, everything in apps/ocean-api will be e2e tests only to keep things simple. Any spec if required should be tackled modularly and separated into their individual packages and tested in isolation.

Boiling down to the last point, to keep the DRY and yet modular all "core" were moved to `ocean-api-client` which are imported into `apps`.

**Comment by eli-lim** [comment]
Some follow-ups after the big merge:
- [ ] the relative imports can be shortened
- [ ] building and running whale's entrypoint main.js throws: node:internal/modules/cjs/loader:936 ; Error: Cannot find module '@defichain/jellyfish-transaction/src/script/_buffer'
- [ ] jest tests currently also get included into the build dir dist: https://github.com/DeFiCh/jellyfish/pull/1259

**Comment by fuxingloh** [comment]
Completed
